const express = require("express")
const router = express.Router()
const productController = require('../Controllers/ProductController')
const cacheMiddleware = require('../MiddleWare/Cache')

router.get('/get-highest-price', productController.findHighestPriceProduct)
router.get('/get-lowest-price', productController.findLowestPriceProduct)
router.post('/create-color', productController.createProductColor)
router.post('/create-size', productController.createProductSize)
router.post('/create-power', productController.createProductPower)
router.post('/create-product', productController.createProduct)
router.post('/create-product-details', productController.createProductDetails)
router.post('/create-product-type', productController.createProductType)
router.post('/create-product-collection', productController.createProductCollection)
router.get('/get-product/:id', productController.getProduct)
router.get('/get-all-product-type', productController.getAllProductType)
router.get('/get-product-ref-props', productController.getProductRefProps)
router.get('/get-all', productController.getAllProduct)
router.get('/get-products-by-type/:id', productController.getProductByType)
router.get('/get-random-products', productController.getRandomProduct)
router.get('/get-product-details/:id', productController.getProductDetails)
router.put('/update-product/:id', productController.updateProduct)
router.delete('/delete-product/:id', productController.deleteProduct)
router.put('/update-product-details/:id', productController.updateProductDetails)
router.delete('/delete-product-details/:id', productController.deleteProductDetails)
module.exports = router